### ISSUE TITLE
How to rebuild library and update sample(s)?

### ISSUE THREAD

**Issue by erizet** [jgauffin/griffin.yo#2]
How do I rebuild the library and update the sample?

From the Packagers bin/debug directory I ran the following.

```
Packager.Console.exe -sourceFolder ..\..\..\..\lib -outputFile ..\..\..\..\Griffin.Yo.ts -rootModule
Griffin.Yo
```

This generates a new ts-file. Trying to build the aspnet demo fails after this. I can see that the pre-compilation script has run and the new Griffin.Yo.ts is copied to the project folder.

**Comment by jgauffin** [comment]
What error do you get?

**Comment by erizet** [comment]
Compilation errors in Griffin.yo.ts. The compiler complains about missing interfaces, like this.

```
Error       Build: Cannot find name 'IViewTarget'.  Demo    C:\test\griffin.yo\demos\aspnet\DemoApp\Griffin.Yo.ts   107
Error   TS2304  Cannot find name 'IViewTarget'. Demo    C:\test\griffin.yo\demos\aspnet\DemoApp\Griffin.Yo.ts   107
```

Worth noting is that I can find 

```
export interface IViewTarget {
```

in Griffin.Yo.ts.

**Comment by jgauffin** [comment]
maila privat. blir lättare. jag får inte samma fel.

Prova köra kompilern från visual studio direkt.
